 # Numpy  
 * (only work on Numbers) 
 * (Based on C language) 
 * (ndarray) 

In [1]:
import numpy as np 

lst = [2,4,6,8]

array = np.array(lst)

array

type(array)

numpy.ndarray

## SIMD: Single Instruction Multiple Data.

In [2]:
lst = [2,4,6,8]

array = np.array(lst)

array

type(array)

array**2

array.dtype

array.ndim

1

### Jitni indexing mai value fetch hojye wo dimension hoga
##### Example: i[0][2] == 2-dimensional 

# Axis
  ### * axis = 0 (row-wise operation)
  ### * axis = 1 (column-wise operation)


In [3]:
arr = np.array([[1,2,3,4],[1,2,3,4]])

In [4]:
arr.sum(axis=0)

array([2, 4, 6, 8])

In [5]:
arr.sum()

arr.sum(axis = 1)

array([10, 10])

In [6]:
# def read_file(filename):
#     from csv import reader
#     return list(reader(open(filename, encoding = "utf-8")))

# .genfromtxt(*file addrease*) == list(reader(open(*file addrease*)))

In [7]:
array = np.genfromtxt("datasets/nyc_taxis.csv" , delimiter = "," , skip_header = 1)

In [8]:
array.ndim

2

In [9]:
array[15:26]     # [rows , columns]

array([[2.016e+03, 1.000e+00, 1.000e+00, 5.000e+00, 1.000e+00, 4.000e+00,
        3.000e+00, 1.209e+01, 1.265e+03, 3.350e+01, 1.300e+00, 5.540e+00,
        1.008e+01, 5.042e+01, 1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, 5.000e+00, 1.000e+00, 2.000e+00,
        4.000e+00, 1.730e+01, 1.588e+03, 5.200e+01, 8.000e-01, 5.540e+00,
        0.000e+00, 5.834e+01, 2.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, 5.000e+00, 1.000e+00, 2.000e+00,
        1.000e+00, 1.374e+01, 2.304e+03, 4.200e+01, 1.300e+00, 0.000e+00,
        5.000e+00, 4.830e+01, 1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, 5.000e+00, 1.000e+00, 4.000e+00,
        2.000e+00, 1.757e+01, 1.654e+03, 5.200e+01, 8.000e-01, 5.540e+00,
        0.000e+00, 5.834e+01, 2.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, 5.000e+00, 1.000e+00, 4.000e+00,
        3.000e+00, 9.500e+00, 1.299e+03, 2.850e+01, 1.300e+00, 0.000e+00,
        5.960e+00, 3.576e+01, 1.000e+00],
       [2.016e+03, 1.000e+00, 1.000e+00, 5.000e+00

In [10]:
# Array[Rows,Colum]
array[:11,9:13]

array([[ 52.  ,   0.8 ,   5.54,  11.65],
       [ 45.  ,   1.3 ,   0.  ,   8.  ],
       [ 36.5 ,   1.3 ,   0.  ,   0.  ],
       [ 26.  ,   1.3 ,   0.  ,   5.46],
       [ 17.5 ,   1.3 ,   0.  ,   0.  ],
       [ 52.  ,   0.8 ,   0.  ,  52.8 ],
       [ 24.5 ,   1.3 ,   0.  ,   6.45],
       [ 21.5 ,   1.3 ,   0.  ,   0.  ],
       [109.5 ,   0.8 ,  11.08,  10.  ],
       [ 36.  ,   1.3 ,   0.  ,   0.  ],
       [ 52.  ,   0.8 ,   5.54,   0.  ]])

In [11]:
Cal_Account = array[:,9:13].sum(axis = 1)

In [12]:
Act = array[:,13]

In [13]:
boolean = Cal_Account == Act

In [14]:
len(boolean)

89560

In [15]:
len(array[boolean])

57151

In [16]:
89560 - 57151

32409

In [17]:
len(array[boolean==False])

32409

In [18]:
array[boolean == False , 12] # Indexing sy maloom krna hai kysy kryngy

array([ 0.  , 11.67,  0.  , ...,  0.  ,  5.  ,  0.  ])

In [19]:
array[:,13] = Cal_Account

In [20]:
np.where(boolean == False)

(array([   10,    12,    13, ..., 89556, 89557, 89559], dtype=int64),)